simter:
  jwt:
    secret-key: @simter.jwt.secret-key@
    require-authorized: @simter.jwt.require-authorized@
  rest.context-path.kv: /kv
gftaxi:
  rest.context-path.traffic-accident: /accident
db:
  platform: @db.platform@
  init-mode: @db.init-mode@
  ddl-auto: @db.ddl-auto@
  host: @db.host@
  port: @db.port@
  name: @db.name@
  username: @db.username@
  password: @db.password@
bc.db:
  host: @bc.db.host@
  port: @bc.db.port@
  name: @bc.db.name@
  username: @bc.db.username@
  password: @bc.db.password@
app.mail:
  imap-host: imap.139.com
  imap-timeout: 25000
  username: gftaxi
  password: gf81800088
  receive-subject: BC事故报案
  receive-last-minutes: 10
  app.mail.mail-id-file: /data/accident/mail-id.txt
app.version:
  traffic-accident: @project.version@
server:
  port: ${port:9102}
  servlet:
    context-path: /
  server-header: @project.artifactId@-@project.version@
spring:
  profiles:
    active: @spring-active-profiles@
  application:
    name: @project.artifactId@-@project.version@
  jpa:
    open-in-view: false
    hibernate.ddl-auto: ${db.ddl-auto:none}  # none | create | create-drop | update | validate
  datasource:
    continue-on-error: false
    sql-script-encoding: UTF-8
    initialization-mode: ${db.init-mode} # embedded|always|never
  jackson:
    default-property-inclusion: NON_EMPTY # see enum of com.fasterxml.jackson.annotation.JsonInclude.Include